image: "python:3.7"

stages:
  - test

include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

semgrep-sast:
  artifacts:
    paths: [gl-sast-report.json]

code_quality:
  stage: test
  artifacts:
    expire_in: 180 days
    expose_as: code_quality
    paths: [gl-code_quality-report.json]

test_job:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --junitxml=report.xml --cov=undulator_analysis_hzb --cov-report term --cov-report xml:coverage/cobertura-coverage.xml
    - coverage xml
    
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
