#set the image
image: python:3.10

#change pip's cache directory
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .


#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"


#test-job1:
#  stage: test
#  script:
#    - echo "This job tests something"

test-job2:
  stage: test
#  image: python:3.10
#  before_script:
#  - pip install .
  script:
    - echo "This job is trying to run pytest"
    - apt-get update -q -y
    - pip install pytest matplotlib pytest-cov h5py
#    - pip install matplotlib
    - pip list
    - pwd
    - ls
    - ls tests/resources
    - ls venv/lib/python3.10/site-packages/undulator_analysis_hzb/
    - cp -r tests venv/lib/python3.10/
    - ls /builds/eddrial/undulator_analysis_hzb/venv/lib/python3.10/site-packages/undulator_analysis_hzb/../../tests/resources/
#    - pytest --cov undulator_analysis_hzb --cov-report term --cov-report xml:coverage/cobertura-coverage.xml
#let's simplify
    - pytest --junitxml=report.xml --cov=undulator_analysis_hzb --cov-report term --cov-report xml:coverage.xml
    - coverage xml
    #modify cobertura xml to replace filename route
#    - sed -i 's=<source>/builds/eddrial/undulator_analysis_hzb</source>=<source>./</source>=g' coverage/cobertura-coverage.xml
    - sed -i 's=venv/lib/python3.10/site-packages/=src/=g' coverage.xml
    - sed -i 's=venv.lib.python3.10.site-packages.=src.=g' coverage.xml
  
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production